### PR TITLE
PR: --json, -j argument to anaconda worker register|list|deregister

### LINKED ISSUE #123: Worker registration info as json at command line interface
For 
```
anaconda worker register|list|deregister
```
provide an --json flag to let the output be a single json for machine reading.

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
Fixes #123.  Output of the commands:

```
anaconda worker register|list|deregister
```
as json if including the --json flag.  This may help with automatic registration of workers or checking registration automatically.  Still when consuming the json output, it is necessary to iterate over the lines in sys.stdin and not try to json.loads the status message that comes out of get_binstar ('Using anaconda-server api site http://api.anaconda.org')

### CODE REVIEW

**Comment by stephenakearns** [comment]
@PeterDSteinberg - can you move to "In progress" or "ready for review" pipeline?

**Comment by PeterDSteinberg** [comment]
The commit I just pushed here silences the "Using API site of ..." message from anaconda-client that was going to standard error.  Now all messages coming out of 

```
anaconda worker register|list|deregister --json
```
are jsonified.

**Comment by srossross** [comment]
@PeterDSteinberg what do you think of doing this in the [clyent library](https://github.com/Anaconda-Server/clyent)

I was thinking this could be a general option if we added a JSON log formatter. for example;
```py
log.info("output is {}", 1, metadata="hello")
```

```
$ test_command 
output is 1

$ test_command  --json
{ "message": "output is 1", args: [1], "metadata": "hello"}

```

**Comment by PeterDSteinberg** [comment]
Sounds good (setting up a json handler in clyent).  I'll work on that.  One question, @srossross,  though is whether the output of a command with --json should be a json on each line of stdout or one list of dictionaries that is json.loaded at once, i.e. do you have to iterate over the rows of stdout and json.load each one.

**Comment by srossross** [comment]
I think each newline should be a new JSON object.

**Comment by PeterDSteinberg** [comment]
See also these other two PRs necessary for this PR to work, notably the TODO list on the clyent PR.
 * [clyent PR 3](https://github.com/Anaconda-Server/clyent/pull/3)
 * [anaconda-client PR 226](https://github.com/Anaconda-Server/anaconda-client/pull/226)

**Comment by PeterDSteinberg** [comment]
@srossross I think these 3 PR's are coming together but there is still the issue that we need to do different log.info call signatures depending on whether it is json formatter or not (json formatter uses curly braces string formatting while other handlers use % formatting).  Does it make sense in this PR to also change the other formatters in clyent so that all of them can use curly braces, e.g.:
```
log.info('Registered {0}', worker_id)
```
If we can change the other formatters to have format methods that handle statements like the above, then we can reduce some of the logging logic in anaconda-build on json vs. not-json.

**Comment by srossross** [comment]
@PeterDSteinberg I don't see how that can be done and not break backwards compatibility.

**Comment by PeterDSteinberg** [comment]
Closing this issue as it is too much work to ensure backward compatibility of loggers for json and not json.

**Pull request closed without merging**
