### PR TITLE
Remove unicode_literals

### LINKED ISSUE #41: Build Worker - pyOpenSSL unicode error on python2
```
[Build Targets]
binstar -q -t %TOKEN% upload --force --user binstar --package chalmers  --channe
l dev C:\Users\binstar\Miniconda\conda-bld\win-64\*.tar.bz2 --build-id 167
Using binstar api site https://api.binstar.org
[TypeError] data must be a byte string
Traceback (most recent call last):
  File "C:\Users\binstar\Miniconda\Scripts\binstar-script.py", line 9, in <modul
e>
    load_entry_point('binstar==0.10.1', 'console_scripts', 'binstar')()
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\scripts\cli.
py", line 94, in main
    description=__doc__, version=version)
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\scripts\cli.
py", line 76, in binstar_main
    return args.main(args)
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\commands\upl
oad.py", line 202, in main
    callback=upload_print_callback(args))
  File "C:\Users\binstar\Miniconda\lib\site-packages\binstar_client\__init__.py"
, line 423, in upload
    s3res = requests.post(s3url, data=data_stream, verify=self.session.verify, t
imeout=10 * 60 * 60, headers=headers)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\api.py", line 108,
 in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\api.py", line 50,
in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\sessions.py", line
 464, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\sessions.py", line
 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\adapters.py", line
 370, in send
    timeout=timeout
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\packages\urllib3\c
onnectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\packages\urllib3\c
onnectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 848, in _send_output
    self.send(message_body)
  File "C:\Users\binstar\Miniconda\lib\httplib.py", line 817, in send
    self.sock.sendall(datablock)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\packages\urllib3\c
ontrib\pyopenssl.py", line 225, in sendall
    sent = self._send_until_done(data)
  File "C:\Users\binstar\Miniconda\lib\site-packages\requests\packages\urllib3\c
ontrib\pyopenssl.py", line 215, in _send_until_done
    return self.connection.send(data)
  File "C:\Users\binstar\Miniconda\lib\site-packages\OpenSSL\SSL.py", line 947,
in send
    raise TypeError("data must be a byte string")
TypeError: data must be a byte string
```

### PR DESCRIPTION
**Pull request by cpcloud**
closes #41

### CODE REVIEW

**Comment by srossross** [comment]
@cpcloud , are you sure this fixes #41 ?

I added most of the __future__ imports in https://github.com/Binstar/binstar-build/commit/ae59bb351768c155027d923e14181bfb8873affa which is not in a release yet.
I don't think that 41 is

**Comment by cpcloud** [comment]
Builds were passing 11 days ago, now they're not. The only significant changes since then were the `unicode_literals` imports

**Comment by cpcloud** [comment]
Were there other changes external to `binstar-build`?

**Comment by stephenakearns** [comment]
@srossross - moving this old PR to "ready for review" - can you suggest a next step here to either move it forward or close it?

**Comment by stephenakearns** [comment]
sorry - @srossross - I just noticed it was already in icebox. I'll leave it there for now.

**Pull request closed without merging**
