### PR TITLE
Fix/add date to log

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
Adds a note to the start of all builds:

Starting build at <ISO DATETIME> UTC

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
Fixes #219

**Comment by dsludwig** [comment]
The build script output does not print to chalmers. This needs a `log.info`, probably somewhere in `Worker.build`

**Comment by PeterDSteinberg** [comment]
I retriggered the test. It is passing on all 6 workers.

**Comment by dsludwig** [comment]
:+1:

**Pull request merged**
