### PR TITLE
Use `build_targets.channels` to set upload channels

### PR DESCRIPTION
**Pull request by dsludwig**
Issue #75 

To test:

* fork and clone http://github.com/Anaconda-server/testci
* add the following content to `.binstar.yml`: 
```
# Tell the build worker we want to upload the resulting conda package
build_targets:
  files: conda
  channels: [foo, bar]
```
* submit a build: `anaconda build submit .`

The resulting uploaded file should have the channels `foo` and `bar`.

### CODE REVIEW

**Comment by dsludwig** [comment]
The failing build is the unrelated Windows issue.

**Comment by srossross** [comment]
@dsludwig can you add a test?

**Comment by dsludwig** [comment]
@srossross tests added!

**Comment by PeterDSteinberg** [comment]
LGTM.  Ran unittests and the test mentioned in comments above.

**Pull request merged**
