### PR TITLE
fix conda-server mentions as dependency

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
Removes 'conda-server' from conda.yaml and setup.py and changes it to 'anaconda-client'.

### CODE REVIEW

**Comment by srossross** [comment]
The tests are failing because anaconda-client does not exist on pypi.
To fix this we need to:

 1. change the `.binstar.yml` line `install conda install binstar pip setuptools` to conda install anaconda-client pip setuptools @PeterDSteinberg
 1. upload `anaconda-client` to pypi @LilaHickey

**Comment by PeterDSteinberg** [comment]
The test appeared to fail for reasons unrelated to the PR.  It failed only on windows.  Does it make sense to merge this PR?

**Comment by srossross** [comment]
I'm not sure why the tests are failing. I think it would be good to figure out why it is failing. (maybe a version mismatch?)

**Comment by PeterDSteinberg** [comment]
@srossross  It now appears to be passing all tests and then is dying with an unexpected error when killing all build processes.  The unexpected error is ```AttributeError: 'module' object has no attribute 'get_pid_list'``` in Miniconda.  The error appears to relate to psutil's versions, where some have ```pids()``` in place of ```get_pid_list```.  See [this forum post](https://forum.manjaro.org/index.php?topic=24300.0) and [this issue](https://github.com/giampaolo/psutil/issues/524)

**Comment by srossross** [comment]
@PeterDSteinberg any ideas on a fix?

**Comment by PeterDSteinberg** [comment]
@srossross  At line 92, in the kill_processes function in C:\Users\binstar\Miniconda\lib\site-packages\conda_build\windows.py we need to change ```psutil.get_pid_list``` to use ```psutil.pids()``` if psutil module does not have an attribute ```get_pid_list```

**Pull request merged**
