### PR TITLE
Fix conda build of binstar-build

### PR DESCRIPTION
**Pull request by tswicegood**
Switched over to explicitly specifying the version number (note how out of sync the `_version.py` file was) and fixed the recipe to build using conda build's latest features.

### CODE REVIEW

**Comment by tswicegood** [comment]
@srossross now that you're back, thoughts about this?

**Comment by srossross** [comment]
@tswicegood this does look like it allows for the creation of pypi packages.

cc @ilanschnell

**Comment by tswicegood** [comment]
@srossross there is one more change I would make based on [these lines][1].  It lets you have build_number 0 without the hash when you're building from a tag.

[1]: https://github.com/conda/conda-env/blob/develop/conda.recipe/meta.yaml#L7-L8

**Comment by srossross** [comment]
Duplicate of #61

**Pull request closed without merging**
